/* Sample listings so the board is not empty while you look at it.
   Every one of these is made up. Nothing here is a real farm or a real phone number. */
window.SAMPLES = [
  { t:'have', c:'Dairy manure', county:'Wayne',      town:'Kidron',        qty:'40 loads, semi tanker',    price:'Free, you haul',      d:0,  who:'Miller Dairy',        ph:'330-555-0148',
    x:'Pit needs pumped down before wheat goes in. Good access off the township road, gravel lot for turning. Would rather it went on ground close by.' },
  { t:'have', c:'Poultry litter', county:'Darke',    town:'Versailles',    qty:'300 ton',                  price:'$18/ton loaded',      d:0,  who:'Hilltop Layer Farm',  ph:'937-555-0192',
    x:'Cleaning two houses out the last week of the month. Dry litter, stacked under roof. Skid loader here to load you.' },
  { t:'truck',c:'Spreader truck', county:'Holmes',   town:'Millersburg',   qty:'2 trucks + tanker',        price:'$95/hr or by the load', d:0, who:'B&J Hauling',        ph:'330-555-0173',
    x:'Running mostly Holmes, Wayne, Tuscarawas. Have a 6,000 gal tanker and a box spreader. Can travel for a bigger job.' },
  { t:'need', c:'Beef manure',    county:'Fairfield',town:'Baltimore',     qty:'Want 10-15 loads',         price:'Will pay hauling',    d:1,  who:'Shaw Farms',          ph:'740-555-0121',
    x:'Putting 60 acres back into corn next spring and the ground is tired. Happy to take solid manure any time after harvest.' },
  { t:'have', c:'Hay - 1st cut',  county:'Ashtabula',town:'Jefferson',     qty:'900 square bales',         price:'$5.50/bale',          d:1,  who:'R. Petersen',         ph:'440-555-0110',
    x:'Mixed grass, baled dry, kept in the mow. No rain on it. Bring your own wagon, I will help load.' },
  { t:'have', c:'Gravel - #57',   county:'Licking',  town:'Hebron',        qty:'Tri-axle loads',           price:'$310/load delivered', d:1,  who:'Clay Pit Stone',      ph:'740-555-0166',
    x:'Delivered within about 30 miles. Also have #8, #304 and screened sand. Same day if you call before 7am.' },
  { t:'have', c:'Horse manure',   county:'Geauga',   town:'Burton',        qty:'8-10 loads a month',       price:'Free',                d:2,  who:'Willow Creek Stable', ph:'440-555-0139',
    x:'Composted about a year, mixed with shavings. Great garden material. Steady all year, we just need it gone.' },
  { t:'need', c:'Straw',          county:'Mercer',   town:'Celina',        qty:'400 bales',                price:'Paying $4.00',        d:2,  who:'Kremer Hogs',         ph:'419-555-0155',
    x:'Wheat straw for bedding. Need it under roof by October. Can pick up if it is within an hour.' },
  { t:'have', c:'Hardwood mulch', county:'Lorain',   town:'Wellington',    qty:'Unlimited, bulk',          price:'$22/yd loaded',       d:2,  who:'Baker Sawmill',       ph:'440-555-0184',
    x:'Double ground, dark. Loading Monday through Saturday. Delivery available up to 25 yards a trip.' },
  { t:'have', c:'Hog manure',     county:'Putnam',   town:'Ottawa',        qty:'500,000 gallon pit',       price:'Free if you pump',    d:3,  who:'Schmitt Finishers',   ph:'419-555-0177',
    x:'Needs done before the ground freezes. Certified applicator preferred. Fields on three sides of the barn if you want to keep it close.' },
  { t:'truck',c:'Dump truck',     county:'Muskingum',town:'Zanesville',    qty:'Tri-axle, available',      price:'$85/hr, 3 hr minimum', d:3, who:'Dale Kinney',         ph:'740-555-0102',
    x:'Hauling stone, dirt, mulch, and dry manure. Southeast Ohio mostly. Retired, so I am flexible on days.' },
  { t:'have', c:'Hay - 2nd cut',  county:'Champaign',town:'Urbana',        qty:'120 round bales, 4x5',     price:'$45/bale',            d:3,  who:'Sutton Livestock',    ph:'937-555-0130',
    x:'Orchard grass and clover, net wrapped, stored inside. Loader on site. Will hold bales with a deposit.' },
  { t:'need', c:'Poultry litter', county:'Highland', town:'Hillsboro',     qty:'Want 200 ton',             price:'Market rate',         d:4,  who:'Gossett Grain',       ph:'937-555-0149',
    x:'Spreading on 300 acres of corn ground. Have our own spreader, just need it delivered to the field edge.' },
  { t:'have', c:'Sawdust',        county:'Holmes',   town:'Mt. Hope',      qty:'Walking floor loads',      price:'$260/load',           d:4,  who:'Yoder Lumber Yard',   ph:'330-555-0163',
    x:'Kiln dried pine and hardwood shavings, good bedding. We load, you haul, or we can arrange a truck.' },
  { t:'have', c:'Topsoil',        county:'Butler',   town:'Oxford',        qty:'2,000 yards',              price:'Free, load it out',   d:4,  who:'Ridgeline Excavating',ph:'513-555-0118',
    x:'Stripped off a building site. Clean black dirt, no rock. Needs to be gone in three weeks before we grade.' },
  { t:'have', c:'Dairy manure',   county:'Auglaize', town:'New Bremen',    qty:'Daily, year round',        price:'Free',                d:5,  who:'Bergman Dairy',       ph:'419-555-0197',
    x:'Solid separated bedding and liquid both available. Looking for a steady neighbor rather than a one time deal.' },
  { t:'need', c:'Gravel',         county:'Vinton',   town:'McArthur',      qty:'6 loads of #4',            price:'Quote me',            d:5,  who:'Toney Ridge Farm',    ph:'740-555-0126',
    x:'Lane washed out again after the June rain. Need base stone hauled about four miles off the state route.' },
  { t:'have', c:'Corn silage',    county:'Mercer',   town:'Coldwater',     qty:'Standing, 90 acres',       price:'$52/ton standing',    d:5,  who:'Link Family Farm',    ph:'419-555-0189',
    x:'Good ears, chopping window is roughly the second week of September. You chop and haul.' },
  { t:'have', c:'Beef manure',    county:'Trumbull', town:'Cortland',      qty:'25 loads solid',           price:'Free, you haul',      d:6,  who:'Hartland Cattle',     ph:'330-555-0157',
    x:'Bedded pack out of the barn. Stacked and turned twice, easy to load, no smell to speak of.' },
  { t:'need', c:'Hay - any cut',  county:'Guernsey', town:'Cambridge',     qty:'Need 60 rounds',           price:'Up to $50',           d:6,  who:'Six Points Ranch',    ph:'740-555-0143',
    x:'Short on winter feed after the dry spell. Grass hay is fine, does not have to be pretty. Will haul it myself.' },
  { t:'have', c:'Screened sand',  county:'Sandusky', town:'Fremont',       qty:'Bulk, by the ton',         price:'$16/ton at the pit',  d:7,  who:'North Star Aggregate',ph:'419-555-0135',
    x:'Bedding sand and mason sand both. Scale on site, open 6:30 to 4:00 weekdays and Saturday mornings.' },
  { t:'truck',c:'Tanker + hoses', county:'Darke',    town:'Greenville',    qty:'Dragline crew, 4 men',     price:'By the acre',         d:7,  who:'Westfall Ag Services',ph:'937-555-0171',
    x:'Certified applicators, incorporation available. Booking fall work now for west central counties.' },
  { t:'have', c:'Oats',           county:'Wyandot',  town:'Upper Sandusky',qty:'1,800 bushel',             price:'$4.10/bu',            d:8,  who:'Cornell Grain Farm',  ph:'419-555-0181',
    x:'Clean oats out of the bin, will load semis or gravity wagons. Straw off the same field also available.' },
  { t:'have', c:'Compost',        county:'Athens',   town:'Albany',        qty:'400 yards',                price:'$28/yd',              d:9,  who:'Hocking Valley Soil', ph:'740-555-0114',
    x:'Finished compost, screened to half inch. Great for market gardens and hoop houses. Delivery by the pickup load too.' },
  { t:'need', c:'Sawdust',        county:'Wayne',    town:'Apple Creek',   qty:'Steady, 2 loads a month',  price:'Will pay freight',    d:10, who:'Bontrager Poultry',   ph:'330-555-0193',
    x:'Bedding for two houses. Need it dry and clean, no walnut. Long term is what I am after, not a one off.' },
  { t:'have', c:'Round bale hay', county:'Adams',    town:'West Union',    qty:'75 bales, outside',        price:'$25/bale',            d:11, who:'Dunbar Hill Farm',    ph:'937-555-0128',
    x:'Stored outside, tops are weathered but the middles are good. Cattle will clean it up. Cheap feed if you can haul it.' }
];
